# ================================================================ #
#                                                                  #
#             A Mango Configuration File                           #
#             by E. Sauthier                                       #
#                                                                  #
# ================================================================ #


###########################################
###              Startup                ###
###########################################

# bar (Waybar)
exec-once=waybar

# Set wallpaper
exec-once=swaybg -i ~/.config/planet.png -m fill

# Redshift
exec-once=gammastep -l 46.94700000:7.44500000 -t 6500:3500 
# w/ coordinates of the BNS

# Notifications
exec-once=mako

# Backups
exec-once=deja-dup

# idle
exec-once=swayidle -w timeout 600 hyprlock before-sleep hyprlock

###########################################
###              Keyboard               ###
###########################################

repeat_rate=30
repeat_delay=500
numlockon=0
xkb_rules_layout=ch
xkb_rules_variant=fr
# Mapping caps-locks to escape for vim
xkb_rules_options= caps:escape

###########################################
###              Trackpad               ###
###########################################
# need relogin to make it apply
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1

###########################################
###               Mouse                 ###
###########################################
# need relogin to make it apply
mouse_natural_scrolling=0

###########################################
###              Monitors               ###
###########################################

# Laptop display: 1080p, 60Hz, no rotation
monitorrule=eDP-1,0.55,2,tile,0,1,0,0,1920,1200,60

# External monitor: 1440p, 144Hz, positioned to the right
monitorrule=HDMI-A-1,0.55,1,tile,0,1,1920,0,2560,1440,144

###########################################
###            Window Rules             ###
###########################################

# Free42 calculator
windowrule=width:500,height:900,isfloating:1,appid:free42

###########################################
###               imports               ###
###########################################

# Appearance config
source=~/.config/mango/appearance.conf

# Keybindings
source=~/.config/mango/keybinds.conf

